device_type: cuda
model_name: large-v3
quantization_type: int8_float16
supported_quantizations:
  cpu:
  - float32
  - int8_float32
  - int8
  cuda:
  - int8_float16
  - float32
  - int8_bfloat16
  - bfloat16
  - int8_float32
  - int8
  - float16
